return {
  { name = "blue",      hex = "#2a5cd1" },
  { name = "blue1",     hex = "#000717" },
  { name = "blue2",     hex = "#01174a" },
  { name = "blue3",     hex = "#062e8a" },
  { name = "blue4",     hex = "#5984e4" },
  { name = "blue5",     hex = "#8dacf1" },
  { name = "blue6",     hex = "#c4d5fb" },

  { name = "cyan",      hex = "#20e5e5" },
  { name = "cyan1",     hex = "#083535" },
  { name = "cyan2",     hex = "#0c7070" },
  { name = "cyan3",     hex = "#16baba" },
  { name = "cyan4",     hex = "#5cf2f2" },
  { name = "cyan5",     hex = "#93fdfd" },
  { name = "cyan6",     hex = "#ccfdfd" },

  { name = "magenta",   hex = "#ee198b" },
  { name = "magenta1",  hex = "#4d092c" },
  { name = "magenta2",  hex = "#850a4a" },
  { name = "magenta3",  hex = "#b60e66" },
  { name = "magenta4",  hex = "#f54da7" },
  { name = "magenta5",  hex = "#f993ca" },
  { name = "magenta6",  hex = "#ffc8e6" },

  { name = "mustard",   hex = "#ebb61d" },
  { name = "mustard1",  hex = "#5c4609" },
  { name = "mustard2",  hex = "#94700b" },
  { name = "mustard3",  hex = "#c79811" },
  { name = "mustard4",  hex = "#f8ce54" },
  { name = "mustard5",  hex = "#fce190" },
  { name = "mustard6",  hex = "#fff0c6" },

  { name = "orange",    hex = "#e29720" },
  { name = "orange1",   hex = "#f72e08" },
  { name = "orange2",   hex = "#7e500c" },
  { name = "orange3",   hex = "#ba7913" },
  { name = "orange4",   hex = "#eaae4d" },
  { name = "orange5",   hex = "#f5cb87" },
  { name = "orange6",   hex = "#fde6c1" },

  { name = "steel",     hex = "#4782b4" },
  { name = "steel1",    hex = "#0a1d2f" },
  { name = "steel2",    hex = "#113c62" },
  { name = "steel3",    hex = "#286395" },
  { name = "steel4",    hex = "#7eaacf" },
  { name = "steel5",    hex = "#cod6e8" },
  { name = "steel6",    hex = "#deadaa" },
}
